// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateCopy(ctx context.Context, arg CreateCopyParams) (Copywriting, error)
	CreateMultipleCopy(ctx context.Context, arg CreateMultipleCopyParams) error
	DeleteCopy(ctx context.Context, arg DeleteCopyParams) error
	GetCopy(ctx context.Context, id int64) (Copywriting, error)
	ListCopies(ctx context.Context, arg ListCopiesParams) ([]Copywriting, error)
}

var _ Querier = (*Queries)(nil)
