// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: publisher.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TempDir       string                 `protobuf:"bytes,1,opt,name=tempDir,proto3" json:"tempDir,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Subscribe     int64                  `protobuf:"varint,5,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	Domain        string                 `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	FileName      string                 `protobuf:"bytes,7,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	PlatformName  string                 `protobuf:"bytes,8,opt,name=platform_name,json=platformName,proto3" json:"platform_name,omitempty"`
	UserId        int64                  `protobuf:"varint,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_publisher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_publisher_proto_rawDescGZIP(), []int{0}
}

func (x *UploadVideoRequest) GetTempDir() string {
	if x != nil {
		return x.TempDir
	}
	return ""
}

func (x *UploadVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadVideoRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UploadVideoRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadVideoRequest) GetSubscribe() int64 {
	if x != nil {
		return x.Subscribe
	}
	return 0
}

func (x *UploadVideoRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UploadVideoRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadVideoRequest) GetPlatformName() string {
	if x != nil {
		return x.PlatformName
	}
	return ""
}

func (x *UploadVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UploadVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_publisher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_publisher_proto_rawDescGZIP(), []int{1}
}

func (x *UploadVideoResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

var File_publisher_proto protoreflect.FileDescriptor

const file_publisher_proto_rawDesc = "" +
	"\n" +
	"\x0fpublisher.proto\x12\x02pb\"\xac\x02\n" +
	"\x12UploadVideoRequest\x12\x18\n" +
	"\atempDir\x18\x01 \x01(\tR\atempDir\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\x12\x1c\n" +
	"\tsubscribe\x18\x05 \x01(\x03R\tsubscribe\x12\x16\n" +
	"\x06domain\x18\x06 \x01(\tR\x06domain\x12\x1b\n" +
	"\tfile_name\x18\a \x01(\tR\bfileName\x12#\n" +
	"\rplatform_name\x18\b \x01(\tR\fplatformName\x12\x17\n" +
	"\auser_id\x18\t \x01(\x03R\x06userId\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\"0\n" +
	"\x13UploadVideoResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoIdB&Z$github.com/pule1234/VideoForge/pb;pbb\x06proto3"

var (
	file_publisher_proto_rawDescOnce sync.Once
	file_publisher_proto_rawDescData []byte
)

func file_publisher_proto_rawDescGZIP() []byte {
	file_publisher_proto_rawDescOnce.Do(func() {
		file_publisher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_publisher_proto_rawDesc), len(file_publisher_proto_rawDesc)))
	})
	return file_publisher_proto_rawDescData
}

var file_publisher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_publisher_proto_goTypes = []any{
	(*UploadVideoRequest)(nil),  // 0: pb.UploadVideoRequest
	(*UploadVideoResponse)(nil), // 1: pb.UploadVideoResponse
}
var file_publisher_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_publisher_proto_init() }
func file_publisher_proto_init() {
	if File_publisher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_publisher_proto_rawDesc), len(file_publisher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_publisher_proto_goTypes,
		DependencyIndexes: file_publisher_proto_depIdxs,
		MessageInfos:      file_publisher_proto_msgTypes,
	}.Build()
	File_publisher_proto = out.File
	file_publisher_proto_goTypes = nil
	file_publisher_proto_depIdxs = nil
}
