// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: publisher.proto

package pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Video         []byte                 `protobuf:"bytes,4,opt,name=video,proto3" json:"video,omitempty"`
	VideoId       int64                  `protobuf:"varint,5,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_publisher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_publisher_proto_rawDescGZIP(), []int{0}
}

func (x *UploadVideoRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UploadVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UploadVideoRequest) GetVideo() []byte {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *UploadVideoRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_publisher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_publisher_proto_rawDescGZIP(), []int{1}
}

func (x *UploadVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadVideoResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UploadVideoResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_publisher_proto protoreflect.FileDescriptor

const file_publisher_proto_rawDesc = "" +
	"\n" +
	"\x0fpublisher.proto\x12\x02pb\x1a\x17validate/validate.proto\"\xab\x01\n" +
	"\x12UploadVideoRequest\x12#\n" +
	"\bplatform\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bplatform\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05video\x18\x04 \x01(\fR\x05video\x12\x19\n" +
	"\bvideo_id\x18\x05 \x01(\x03R\avideoId\"f\n" +
	"\x13UploadVideoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatformB&Z$github.com/pule1234/VideoForge/pb;pbb\x06proto3"

var (
	file_publisher_proto_rawDescOnce sync.Once
	file_publisher_proto_rawDescData []byte
)

func file_publisher_proto_rawDescGZIP() []byte {
	file_publisher_proto_rawDescOnce.Do(func() {
		file_publisher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_publisher_proto_rawDesc), len(file_publisher_proto_rawDesc)))
	})
	return file_publisher_proto_rawDescData
}

var file_publisher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_publisher_proto_goTypes = []any{
	(*UploadVideoRequest)(nil),  // 0: pb.UploadVideoRequest
	(*UploadVideoResponse)(nil), // 1: pb.UploadVideoResponse
}
var file_publisher_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_publisher_proto_init() }
func file_publisher_proto_init() {
	if File_publisher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_publisher_proto_rawDesc), len(file_publisher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_publisher_proto_goTypes,
		DependencyIndexes: file_publisher_proto_depIdxs,
		MessageInfos:      file_publisher_proto_msgTypes,
	}.Build()
	File_publisher_proto = out.File
	file_publisher_proto_goTypes = nil
	file_publisher_proto_depIdxs = nil
}
